name: Fetch Secret from Azure Key Vault

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  fetch-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure using Federated Identity Credential
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          federated-token: ${{ secrets.GITHUB_TOKEN }}
          allow-no-subscriptions: true

      - name: Set up Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Fetch secret from Azure Key Vault
        id: get-secret
        run: |
          az keyvault secret show --vault-name KeyVaultGithub --name secretgit --query value -o tsv > secret.txt

      - name: Display secret
        run: cat secret.txt

      - name: Print githubtoken
        run: |
           echo"Github token ${{secrets.GITHUB_TOKEN}}"
