name: Fetch Secret from Azure Key Vault

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  fetch-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure using Federated Identity Credential
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          federated-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch secret from Azure Key Vault
        id: get-secret
        uses: azure/azure-sdk-for-js/keyvault-secrets@v1
        with:
          vault-name: KeyVaultGithub
          secret-name: secretgit

      - name: Display secret
        run: echo "Secret fetched:${{ steps.get-secret.outputs.secret }}"
